// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// JWTMiddelware is an autogenerated mock type for the JWTMiddelware type
type JWTMiddelware struct {
	mock.Mock
}

// ValidateJWT provides a mock function with given fields: handler
func (_m *JWTMiddelware) ValidateJWT(handler http.HandlerFunc) http.HandlerFunc {
	ret := _m.Called(handler)

	var r0 http.HandlerFunc
	if rf, ok := ret.Get(0).(func(http.HandlerFunc) http.HandlerFunc); ok {
		r0 = rf(handler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.HandlerFunc)
		}
	}

	return r0
}
