// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// PlayerController is an autogenerated mock type for the PlayerController type
type PlayerController struct {
	mock.Mock
}

// DeletePlayerById provides a mock function with given fields: w, req
func (_m *PlayerController) DeletePlayerById(w http.ResponseWriter, req *http.Request) {
	_m.Called(w, req)
}

// GetPlayer provides a mock function with given fields: w, req
func (_m *PlayerController) GetPlayer(w http.ResponseWriter, req *http.Request) {
	_m.Called(w, req)
}

// GetPlayers provides a mock function with given fields: w, req
func (_m *PlayerController) GetPlayers(w http.ResponseWriter, req *http.Request) {
	_m.Called(w, req)
}

// PatchPlayer provides a mock function with given fields: w, req
func (_m *PlayerController) PatchPlayer(w http.ResponseWriter, req *http.Request) {
	_m.Called(w, req)
}

// PostPlayer provides a mock function with given fields: w, req
func (_m *PlayerController) PostPlayer(w http.ResponseWriter, req *http.Request) {
	_m.Called(w, req)
}
