// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// UserController is an autogenerated mock type for the UserController type
type UserController struct {
	mock.Mock
}

// Login provides a mock function with given fields: w, req
func (_m *UserController) Login(w http.ResponseWriter, req *http.Request) {
	_m.Called(w, req)
}

// Signup provides a mock function with given fields: w, req
func (_m *UserController) Signup(w http.ResponseWriter, req *http.Request) {
	_m.Called(w, req)
}
